### ISSUE TITLE
Aggregation type

### ISSUE THREAD

**Issue by Gouiaa** [Stick-To/DLA-tensorflow#2]
Thanks, @Stick-To for sharing your code. I remark that you only used the IDA aggregation but in the original paper DLA-34, ... are all based on IDA and HDA?

**Comment by Stick-To** [comment]
HDA is implemented with  function _dla_generator()  intra-stage,  IDA is implemented by residual connect inter-stages.   function _dla_generator() is a recursive function

**Comment by Gouiaa** [comment]
Thanks for your answer @Stick-To. I see. However, based on the paper, stage 1 is 7*7 conv followed by a basic_block (basic residual block). Stage 2 is only a basic block... I don't see this in the code. (I see that your implementation follows the figure 3)! 

Another question about the dense version of DLA (figure 4), I think we need to add only the IDA aggregation between stages and the up-sampling.

**Comment by Stick-To** [comment]
I have not write the up-sampling code (figure 4),  I have just use DLA as a classifier that needn't up-sampling operation. And about the Stage 2, the paper says that the stage 2 is a basic block, but the official code does not.

**Comment by Gouiaa** [comment]
@Stick-To, thanks. Exactly there is a mismatch between the official Pytorch code and the paper.
